### ISSUE TITLE
Help with F413 Nucleo

### ISSUE THREAD

**Issue by jo5huajohn** [hubmartin/WS2812B_STM32F4#11]
The program runs perfectly well, but the LEDs do not light up according to the code, they just randomly light up and turning off they do not light again. Also, on connecting to PC0 (output pin) it turns off all the LEDs leading me to think that the code is running, but is not lighting up the LEDs. Please help!

**Comment by hubmartin** [comment]
Please send code! :)
I would need bit more information to understand what's happening.
What IDE and how did you created the project. My code is a library so I'm missing info how the library is used in your code.
Do you have enabled some code optimization -O2 ?
Check with debugger/debug prints that the code is jumping to DMA and timer interrupts.
`DMA2_Stream2_IRQHandler` and `TIM1_UP_TIM10_IRQHandler`
Each PC0 - PC3 has different effect, try other pins.
Do you have  oscilloscope or logic analyzer? Please send traces to I could check what the hardware sees.
